---
title: "De Amorim"
format: html
toc: true
---
# Introduction
## Study organisation
### Question 1

```{r}
#| label: data loading
#| message: false
#| warning: false
  
library(readr)
courses <- read_csv("Database/courses.csv")


```

### Question 2

```{r}
#| label: data display

library(knitr)
kable(courses)

```

## Students
### Question 3

```{r}
#| label: Question 3
#| message: false
#| warning: false

library(tidyverse)
students <- read_csv("Database/students.csv")
spec(students)

students <-
  students |>
  mutate(sex = factor(sex, 
                      levels = c("M", "F"),
                      labels = c("Male", "Female")),
         group = factor(group),
         id = as.integer(group))

```

The birth_date column of the students data frame is of class `r class(students$birth_date)`.
The birth_date column of the students data frame is of class `r class(students$sex)`.

## Grades
### Question 4 

```{r}

grades <- read_delim("Database/grades.csv", 
    delim = ":", 
    na = "$")

```

# Student population analysis
## Question 5

```{r}
library(ggplot2)
library(ggthemes)

ggplot(students, aes(y = group))+
  geom_bar(aes(fill = group))+
  theme_clean()+
  labs(
    title = "Distribution of students by group"
  )+
  theme(legend.position = "none")

```


## Question 6 

```{r}
ggplot(students, aes(y = group))+
  geom_bar(aes(fill = sex))+
  theme_clean()+
  labs(
    title = "Distribution of students by group and by gender"
  )
```

